const std = @import("std");

pub const Blk14 = struct {
    carbn: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    tcuptk: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    tcsnc: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    tzuptk: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    tzsnc: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    tpuptk: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    tpsnc: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    tzupfx: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    tco2t: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    balc: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    baln: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    balp: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    hcsnc: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    hzsnc: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    hpsnc: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    hcuptk: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    hzuptk: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    hpuptk: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    znpp: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    tcsn0: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    ctran: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    rnh3c: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    rsetc: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    rsetn: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    rsetp: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    hvstc: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    hvstn: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    hvstp: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    thvstc: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    thvstn: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    tnh3c: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    thvstp: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    tco2a: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    vco2f: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    vch4f: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    voxyf: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    vnh3f: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    vn2of: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    vpo4f: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    tzsn0: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),
    tpsn0: comptime [jx][jy][jp]f32 = std.mem.zeroes([jx][jy][jp]f32),

    pub fn init() Blk14 {
        return .{};
    }
};
