const std = @import("std");

pub const Blk13c = struct {
    cfosc: comptime [jx][jy][jz + 1][6][4]f32 = std.mem.zeroes([jx][jy][jz + 1][6][4]f32),
    cnos: comptime [jx][jy][jz + 1][6][4]f32 = std.mem.zeroes([jx][jy][jz + 1][6][4]f32),
    cposc: comptime [jx][jy][jz + 1][6][4]f32 = std.mem.zeroes([jx][jy][jz + 1][6][4]f32),
    xoqcs: comptime [jx][jy][jz + 1][6]f32 = std.mem.zeroes([jx][jy][jz + 1][6]f32),
    xoqns: comptime [jx][jy][jz + 1][6]f32 = std.mem.zeroes([jx][jy][jz + 1][6]f32),
    xoqps: comptime [jx][jy][jz + 1][6]f32 = std.mem.zeroes([jx][jy][jz + 1][6]f32),
    xoqas: comptime [jx][jy][jz + 1][6]f32 = std.mem.zeroes([jx][jy][jz + 1][6]f32),
    cnomc: comptime [6][7][3]f32 = std.mem.zeroes([6][7][3]f32),
    cpomc: comptime [6][7][3]f32 = std.mem.zeroes([6][7][3]f32),
    xnh4s: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    xno3s: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    xh2ps: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    xnh4b: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    xno3b: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    xn2gs: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    xh2bs: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    vlnh4: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    vlnhb: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    vlno3: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    vlnob: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    vlpo4: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    vlpob: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    wdnhb: comptime [jx][jy][jz]f32 = std.mem.zeroes([jx][jy][jz]f32),
    dpnhb: comptime [jx][jy][jz]f32 = std.mem.zeroes([jx][jy][jz]f32),
    wdnob: comptime [jx][jy][jz]f32 = std.mem.zeroes([jx][jy][jz]f32),
    dpnob: comptime [jx][jy][jz]f32 = std.mem.zeroes([jx][jy][jz]f32),
    wdpo4: comptime [jx][jy][jz]f32 = std.mem.zeroes([jx][jy][jz]f32),
    dppo4: comptime [jx][jy][jz]f32 = std.mem.zeroes([jx][jy][jz]f32),
    dpnh4: comptime [jx][jy]f32 = std.mem.zeroes([jx][jy]f32),
    dpno3: comptime [jx][jy]f32 = std.mem.zeroes([jx][jy]f32),
    fl: comptime [2]f32 = std.mem.zeroes([2]f32),
    rinho: comptime [jx][jy][jz + 1][6][7]f32 = std.mem.zeroes([jx][jy][jz + 1][6][7]f32),
    rinoo: comptime [jx][jy][jz + 1][6][7]f32 = std.mem.zeroes([jx][jy][jz + 1][6][7]f32),
    ripoo: comptime [jx][jy][jz + 1][6][7]f32 = std.mem.zeroes([jx][jy][jz + 1][6][7]f32),
    h2gsh: comptime [jx][jy][jz]f32 = std.mem.zeroes([jx][jy][jz]f32),
    xcodfr: comptime [jx][jy]f32 = std.mem.zeroes([jx][jy]f32),
    xchdfr: comptime [jx][jy]f32 = std.mem.zeroes([jx][jy]f32),
    xoxdfr: comptime [jx][jy]f32 = std.mem.zeroes([jx][jy]f32),
    xngdfr: comptime [jx][jy]f32 = std.mem.zeroes([jx][jy]f32),
    xn2dfr: comptime [jx][jy]f32 = std.mem.zeroes([jx][jy]f32),
    xn3dfr: comptime [jx][jy]f32 = std.mem.zeroes([jx][jy]f32),
    xhgfr: comptime [jx][jy]f32 = std.mem.zeroes([jx][jy]f32),
    rvmb2: comptime [jx][jy][jz + 1][6][7]f32 = std.mem.zeroes([jx][jy][jz + 1][6][7]f32),
    rvmb3: comptime [jx][jy][jz + 1][6][7]f32 = std.mem.zeroes([jx][jy][jz + 1][6][7]f32),
    rvmb4: comptime [jx][jy][jz + 1][6][7]f32 = std.mem.zeroes([jx][jy][jz + 1][6][7]f32),
    rvmbc: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    rvmxc: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    ch2gg: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),
    xzhys: comptime [jx][jy][jz + 1]f32 = std.mem.zeroes([jx][jy][jz + 1]f32),

    pub fn init() Blk13c {
        return .{};
    }
};
