const std = @import("std");
const config = @import("config");
const jx = config.ewgridsmax;
const jy = config.nsgridsmax;
const jz = config.soillayersmax;
const jc = config.canopymax;

pub const Blk18a = struct {
    csnt: [jx][jy][jz + 1][2][4]f32,
    zsnt: [jx][jy][jz + 1][2][4]f32,
    psnt: [jx][jy][jz + 1][2][4]f32,
    tdfomc: [jx][jy][jz][5]f32,
    tdfomn: [jx][jy][jz][5]f32,
    tdfomp: [jx][jy][jz][5]f32,
    tupwtr: [jx][jy][jz + 1]f32,
    tupht: [jx][jy][jz + 1]f32,
    tcofla: [jx][jy][jz]f32,
    toxfla: [jx][jy][jz]f32,
    tchfla: [jx][jy][jz]f32,
    tn2fla: [jx][jy][jz]f32,
    tnhfla: [jx][jy][jz]f32,
    tlco2p: [jx][jy][jz]f32,
    tloxy: [jx][jy][jz]f32,
    tlch4p: [jx][jy][jz]f32,
    tln2op: [jx][jy][jz]f32,
    tlnh3p: [jx][jy][jz]f32,
    tco2s: [jx][jy][jz]f32,
    tupoxs: [jx][jy][jz]f32,
    tupchs: [jx][jy][jz]f32,
    tupn2s: [jx][jy][jz]f32,
    tupn3s: [jx][jy][jz]f32,
    tupnh4: [jx][jy][jz]f32,
    tupno3: [jx][jy][jz]f32,
    tuph2p: [jx][jy][jz]f32,
    tupn3b: [jx][jy][jz]f32,
    tupnhb: [jx][jy][jz]f32,
    tupnob: [jx][jy][jz]f32,
    tuph2b: [jx][jy][jz]f32,
    tupnf: [jx][jy][jz]f32,
    tco2p: [jx][jy][jz]f32,
    tupoxp: [jx][jy][jz]f32,
    rtdnt: [jx][jy][jz]f32,
    tuph1p: [jx][jy][jz]f32,
    tuph1b: [jx][jy][jz]f32,
    arlft: [jx][jy][jc]f32,
    arstt: [jx][jy][jc]f32,
    wglft: [jx][jy][jc]f32,
    arlfc: [jx][jy]f32,
    arstc: [jx][jy]f32,
    tevapp: [jx][jy]f32,
    tevapc: [jx][jy]f32,
    tengyc: [jx][jy]f32,
    thflxc: [jx][jy]f32,
    tvolwp: [jx][jy]f32,
    gpp: [jx][jy]f32,
    reco: [jx][jy]f32,
    tco2z: [jx][jy]f32,
    toxyz: [jx][jy]f32,
    tch4z: [jx][jy]f32,
    tn2oz: [jx][jy]f32,
    tnh3z: [jx][jy]f32,
    thrmc: [jx][jy]f32,
    tcnet: [jx][jy]f32,
    zcsnc: [jx][jy]f32,
    zzsnc: [jx][jy]f32,
    zpsnc: [jx][jy]f32,
    arlss: [jx][jy]f32,
    tccan: [jx][jy]f32,

    pub fn init() Blk18a {
        return std.mem.zeroInit(Blk18a, .{});
    }
};
