const std = @import("std");
const config = @import("config");
const jx = config.ewgridsmax;
const jy = config.nsgridsmax;
const jz = config.soillayersmax;

pub const Blk2c = struct {
    cocu: [jx][jy][jz][5]f32,
    conu: [jx][jy][jz][5]f32,
    coau: [jx][jy][jz][5]f32,
    copu: [jx][jy][jz][5]f32,
    cn4u: [jx][jy][jz]f32,
    cn3u: [jx][jy][jz]f32,
    cnou: [jx][jy][jz]f32,
    ch2pu: [jx][jy][jz]f32,
    cnzu: [jx][jy][jz]f32,
    calu: [jx][jy][jz]f32,
    cfeu: [jx][jy][jz]f32,
    chyu: [jx][jy][jz]f32,
    ccau: [jx][jy][jz]f32,
    cmgu: [jx][jy][jz]f32,
    cnau: [jx][jy][jz]f32,
    ckau: [jx][jy][jz]f32,
    cohu: [jx][jy][jz]f32,
    csou: [jx][jy][jz]f32,
    cclu: [jx][jy][jz]f32,
    cc3u: [jx][jy][jz]f32,
    chcu: [jx][jy][jz]f32,
    cal1u: [jx][jy][jz]f32,
    cal2u: [jx][jy][jz]f32,
    cal3u: [jx][jy][jz]f32,
    cal4u: [jx][jy][jz]f32,
    calsu: [jx][jy][jz]f32,
    cfe1u: [jx][jy][jz]f32,
    cfe2u: [jx][jy][jz]f32,
    cfe3u: [jx][jy][jz]f32,
    cfe4u: [jx][jy][jz]f32,
    cfesu: [jx][jy][jz]f32,
    ccaou: [jx][jy][jz]f32,
    ccacu: [jx][jy][jz]f32,
    ccahu: [jx][jy][jz]f32,
    ccasu: [jx][jy][jz]f32,
    cmgou: [jx][jy][jz]f32,
    cmgcu: [jx][jy][jz]f32,
    cmghu: [jx][jy][jz]f32,
    cmgsu: [jx][jy][jz]f32,
    cnacu: [jx][jy][jz]f32,
    cnasu: [jx][jy][jz]f32,
    ckasu: [jx][jy][jz]f32,
    ch0pu: [jx][jy][jz]f32,
    ch1pu: [jx][jy][jz]f32,
    ch3pu: [jx][jy][jz]f32,
    cf1pu: [jx][jy][jz]f32,
    cf2pu: [jx][jy][jz]f32,
    cc0pu: [jx][jy][jz]f32,
    cc1pu: [jx][jy][jz]f32,
    cc2pu: [jx][jy][jz]f32,
    cm1pu: [jx][jy][jz]f32,
    ccoq: [jx][jy]f32,
    cchq: [jx][jy]f32,
    coxq: [jx][jy]f32,
    cnnq: [jx][jy]f32,
    cn2q: [jx][jy]f32,
    ccou: f32,
    cchu: f32,
    coxu: f32,
    cnnu: f32,
    cn2u: f32,
    bkrs: [3]f32,

    pub fn init() Blk2c {
        return std.mem.zeroInit(Blk2c, .{});
    }
};
