const std = @import("std");
const config = @import("config");
const jx = config.ewgridsmax;
const jy = config.nsgridsmax;
const jz = config.soillayersmax;
const jh = jx + 1;
const jv = jy + 1;

pub const Blk8a = struct {
    rsc: [jx][jy][jz + 1][3]f32,
    rsn: [jx][jy][jz + 1][3]f32,
    rsp: [jx][jy][jz + 1][3]f32,
    fmpr: [jx][jy][jz + 1]f32,
    cdepth: [jx][jy][jz + 1]f32,
    bkds: [jx][jy][jz + 1]f32,
    fc: [jx][jy][jz + 1]f32,
    wp: [jx][jy][jz + 1]f32,
    scnv: [jx][jy][jz + 1]f32,
    ph: [jx][jy][jz + 1]f32,
    ccapd: [jx][jy][jz + 1]f32,
    ccaph: [jx][jy][jz + 1]f32,
    corgc: [jx][jy][jz + 1]f32,
    rock: [jx][jy][jz]f32,
    scnh: [jx][jy][jz]f32,
    csand: [jx][jy][jz]f32,
    csilt: [jx][jy][jz]f32,
    cclay: [jx][jy][jz]f32,
    fhol: [jx][jy][jz]f32,
    phol: [jx][jy][jz]f32,
    dhol: [jx][jy][jz]f32,
    hrad: [jx][jy][jz]f32,
    bkdsi: [jx][jy][jz]f32,
    cec: [jx][jy][jz]f32,
    aec: [jx][jy][jz]f32,
    corgr: [jx][jy][jz]f32,
    corgn: [jx][jy][jz]f32,
    corgp: [jx][jy][jz]f32,
    cnh4: [jx][jy][jz]f32,
    cno3: [jx][jy][jz]f32,
    cpo4: [jx][jy][jz]f32,
    cal: [jx][jy][jz]f32,
    cfe: [jx][jy][jz]f32,
    cca: [jx][jy][jz]f32,
    cmg: [jx][jy][jz]f32,
    cna: [jx][jy][jz]f32,
    cka: [jx][jy][jz]f32,
    cso4: [jx][jy][jz]f32,
    ccl: [jx][jy][jz]f32,
    caloh: [jx][jy][jz]f32,
    cfeoh: [jx][jy][jz]f32,
    ccaco: [jx][jy][jz]f32,
    ccaso: [jx][jy][jz]f32,
    calpo: [jx][jy][jz]f32,
    gkc4: [jx][jy][jz]f32,
    gkch: [jx][jy][jz]f32,
    gkca: [jx][jy][jz]f32,
    gkcm: [jx][jy][jz]f32,
    gkcn: [jx][jy][jz]f32,
    gkck: [jx][jy][jz]f32,
    thw: [jx][jy][jz]f32,
    thi: [jx][jy][jz]f32,
    porosi: [jx][jy][jz]f32,
    fholi: [jx][jy][jz]f32,
    corgci: [jx][jy][jz]f32,
    nhol: [jx][jy][jz]i32,
    psifc: [jx][jy]f32,
    psiwp: [jx][jy]f32,
    albs: [jx][jy]f32,
    tsed: [jx][jy]f32,
    dets: [jx][jy]f32,
    dete: [jx][jy]f32,
    cer: [jx][jy]f32,
    xer: [jx][jy]f32,
    slope: [jx][jy][4]f32,
    cdepthi: [jx][jy]f32,
    ptdsnu: [jx][jy]f32,
    vls: [jx][jy]f32,
    sed: [jx][jy]f32,
    nu: [jx][jy]i32,
    nui: [jx][jy]i32,
    nj: [jx][jy]i32,
    nk: [jx][jy]i32,
    num: [jx][jy]i32,
    isoilr: [jx][jy]i32,
    nli: [jh][jv]i32,
    nl: [jh][jv]i32,

    pub fn init() Blk8a {
        return std.mem.zeroInit(Blk8a, .{});
    }
};
